name: Deploy dist

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          cd CiCd
          npm install
          npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: CiCd/dist # vite হলে dist, CRA হলে build

  deploy:
    needs: build #er karone first a test hobe pore deploy hobe
    runs-on: ubuntu-latest

    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: react-build

      - name: Show files
        run: ls -R

      - name: Deploy
        run: echo "🚀 Deploy Successful"
